# Generated by Django 4.1.5 on 2023-06-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('estoque_produto', models.IntegerField(verbose_name='Quantidade de Produto em Estoque')),
            ],
        ),
    ]
