# Generated by Django 4.2.2 on 2023-06-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('sobre_nome_cliente', models.CharField(max_length=100, verbose_name='Sobre Nome do Cliente')),
                ('email_cliente', models.EmailField(max_length=100, verbose_name='Email do CLiente')),
            ],
        ),
    ]
